name: ZAP DAST

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  issues: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: ${{ secrets.APPLICATION_URL }}
          cmd_options: '-t ${{ secrets.APPLICATION_URL }} -r zap_report.html'
          issue_title: 'ZAP Report'


      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: ZAP Report
          path: zap_report.html
